calendoola_web/calendoola_web/urls.py
from django.conf.urls import (
    url,
    include,
)

urlpatterns = [
    url(r'^', include('caleweb.urls')),
]

calendoola_web/caleweb/urls.py
import django.contrib.auth.views as auth_views
from django.conf.urls import (
    url,
    include,
)
from django.views.generic import RedirectView

from . import views

task_patterns = [
    url(r'^$', views.TaskListView.as_view(), name='all'),
    url(r'^search/$', views.TaskListSearchView.as_view(), name='search'),
    url(r'^new/$', views.TaskCreateView.as_view(), name='new'),
    url(r'^archive/$', views.TaskArchiveListView.as_view(), name='archive'),
    url(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.TaskUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/restore/$', views.restore_task, name='restore'),
    url(r'^(?P<pk>\d+)/finish/$', views.finish_task, name='finish'),
    url(r'^(?P<pk>\d+)/share/$', views.share_task, name='share'),
    url(r'^(?P<pk>\d+)/move/$', views.move_task, name='move'),
    url(r'^(?P<pk>\d+)/remove/$', views.TaskDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/unshare/(?P<name>\w+)/$', views.unshare_task, name='unshare'),
    url(r'^(?P<pk>\d+)/add-subtask', views.AddSubtaskView.as_view(), name='add-subtask')
]

plan_patterns = [
    url(r'^$', views.PlanListView.as_view(), name='all'),
    url(r'^new/$', views.PlanCreateView.as_view(), name='new'),
    url(r'^(?P<pk>\d+)/remove/$', views.PlanDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/set-state/$', views.plan_set_state, name='set-state'),
    url(r'^(?P<pk>\d+)/edit/$', views.PlanUpdateView.as_view(), name='edit'),
]

reminder_patterns = [
    url(r'^$', views.ReminderListView.as_view(), name='all'),
    url(r'^new/$', views.ReminderCreateView.as_view(), name='new'),
    url(r'^(?P<pk>\d+)/$', views.ReminderDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/remove/$', views.ReminderDeleteView.as_view(), name='remove'),
    url(r'^(?P<pk>\d+)/set-state/$', views.reminder_set_state, name='set-state'),
    url(r'^(?P<pk>\d+)/edit/$', views.ReminderUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/add-task/$', views.reminder_add_task, name='add-task'),
    url(r'^(?P<pk>\d+)/detach/(?P<task>\d+)/$', views.reminder_detach_task, name='detach-task')
]

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='tasks'), name='homepage'),
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^tasks/', include(task_patterns, namespace='tasks')),
    url(r'^plans/', include(plan_patterns, namespace='plans')),
    url(r'^reminders/', include(reminder_patterns, namespace='reminders')),
]

calendoola_web/caleweb/forms.py
from calelib.constants import Constants
from calelib.models import (
    Task,
    Plan,
)
from django import forms

from .value_parsers import parse_period


class TaskShareForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self._users = kwargs.pop('users')
        super(TaskShareForm, self).__init__(*args, **kwargs)
        self.fields['user_to'].choices = ((u.nickname, u.nickname) for u in self._users)

    user_to = forms.ChoiceField(widget=forms.Select, label='Users')


class TaskCreateForm(forms.ModelForm):
    parent_task = forms.ModelChoiceField(empty_label='Do not make subtask',
                                         queryset=Task.objects.none(),
                                         required=False)

    def __init__(self, tasks, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        self.fields['parent_task'].queryset = tasks

    class Meta:
        model = Task
        fields = ['info', 'deadline', 'priority', 'tags']


class AddSubtaskForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self._parent_task = kwargs.pop('parent_task')
        super(AddSubtaskForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Task
        fields = ['info', 'deadline', 'priority', 'tags']

    def clean_deadline(self):
        if self._parent_task.deadline and self.cleaned_data['deadline']:
            if self._parent_task.deadline < self.cleaned_data['deadline']:
                self.add_error('deadline', 'Deadline of child task can not exceed {}'
                               .format(self._parent_task.deadline.strftime('%d %m %Y %H:%M ')))


class TaskMoveForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self._tasks = kwargs.pop('tasks')
        super(TaskMoveForm, self).__init__(*args, **kwargs)
        self.fields['task_to'].choices = ((t.pk, t.info) for t in self._tasks)
        if len(self.fields['task_to'].choices) == 0:
            self.fields['task_to'].widget = forms.HiddenInput()

    to_main = forms.BooleanField(required=False, help_text='Pass task to main view',
                                 widget=forms.Select(choices=((False, 'No'),
                                                              (True, 'Yes')
                                                              )))
    task_to = forms.ChoiceField(label='Available tasks')


class PlanModelForm(forms.ModelForm):
    period = forms.CharField(widget=forms.TextInput(), initial='')

    class Meta:
        model = Plan
        fields = ['info', 'time_at', 'period_type']

    def clean(self):
        cleaned_data = super(PlanModelForm, self).clean()
        try:
            parse_period(cleaned_data['period_type'], cleaned_data['period'])
        except ValueError:
            if cleaned_data['period_type'] == Constants.REPEAT_DAY:
                self.add_error('period', 'Enter only digit')
            elif cleaned_data['period_type'] == Constants.REPEAT_WEEKDAY:
                self.add_error('period', 'Enter only full weekday names')
            else:
                self.add_error('period', 'Follow example: "25 May, October"')


class ReminderAddTaskForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self._tasks = kwargs.pop('task')
        super(ReminderAddTaskForm, self).__init__(*args, **kwargs)
        self.fields['task'].choices = ((t.pk, t.info) for t in self._tasks)

    task = forms.ChoiceField(label='Available tasks', required=False)

calendoola_web/caleweb/views.py
from calelib import CycleError
from calelib.crud import Calendoola
from calelib.models import (
    Task,
    Plan,
    Reminder,
)
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .forms import (
    TaskShareForm,
    TaskCreateForm,
    PlanModelForm,
    ReminderAddTaskForm,
    AddSubtaskForm,
    TaskMoveForm,
)
from .value_parsers import (
    parse_period,
    parse_period_to_view,
)

db = Calendoola()


def signup(request):
    if request.user.is_authenticated:
        return redirect('homepage')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('homepage')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


# ###R###E###G###I###S###T###R###A###T###I###O###N##########

@login_required
def finish_task(request, pk):
    username = request.user.username
    task = db.get_tasks(username, pk)
    task.finish()
    return redirect('homepage')


@login_required
def restore_task(request, pk):
    username = request.user.username
    task = db.get_tasks(username, pk)
    task.restore()
    return redirect('homepage')


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'caleweb/task_all.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        if self.request.GET.get('order'):
            return db.get_sorted_tasks(username, self.request.GET.get('order'), self.request.GET.get('vec'))
        return db.get_tasks(username)


class TaskListSearchView(TaskListView):

    def get_queryset(self):
        username = self.request.user.username
        query = self.request.GET.get('data')
        result = db.get_tasks(username)
        if query:
            result_info = db.get_tasks(username, info=query, primary=False)
            result_tags = db.get_tasks(username, tags=query, primary=False)
            result = result_info | result_tags
        return result


class TaskArchiveListView(LoginRequiredMixin, ListView):
    template_name = 'caleweb/task_all.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        username = self.request.user.username
        return db.get_tasks(username=username, archive=True)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'caleweb/task_detail.html'

    def get_object(self, queryset=None):
        return db.get_tasks(username=self.request.user.username, task_id=self.kwargs['pk'])


class TaskCreateView(LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = 'caleweb/instance-form.html'

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs.update({'tasks': db.get_tasks(self.request.user.username, primary=False)})
        return kwargs

    def form_valid(self, form):
        username = self.request.user.username
        new_task = form.save(commit=False)
        new_task.owner = db.get_users(self.request.user.username)
        new_task.save()
        parent_task = form.cleaned_data['parent_task']
        parent_task.add_subtask(new_task) if parent_task else db.add_completed(username, 'task', new_task)
        return redirect('tasks:detail', new_task.pk)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'caleweb/instance-form.html'
    fields = ['info', 'deadline', 'priority', 'tags']

    def get_success_url(self):
        return reverse_lazy('tasks:detail', args=(self.object.pk,))


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'caleweb/confirm_delete-form.html'
    success_url = reverse_lazy('homepage')

    def get_object(self, queryset=None):
        username = self.request.user.username
        task = db.get_tasks(username=username,
                            task_id=self.kwargs['pk'])
        return task

    def delete(self, request, *args, **kwargs):
        username = self.request.user.username
        db.remove_task(username, self.kwargs['pk'])
        return redirect('homepage')


class AddSubtaskView(CreateView):
    form_class = AddSubtaskForm
    template_name = 'caleweb/instance-form.html'

    def get_form_kwargs(self):
        kwargs = super(AddSubtaskView, self).get_form_kwargs()
        parent_task = db.get_tasks(self.request.user.username, self.kwargs['pk'])
        kwargs.update({'parent_task': parent_task})
        return kwargs

    def form_valid(self, form):
        username = self.request.user.username
        parent_task = db.get_tasks(username, self.kwargs['pk'])
        new_task = form.save(commit=False)
        new_task.owner = db.get_users(self.request.user.username)
        new_task.save()
        parent_task.add_subtask(new_task)
        return redirect('tasks:detail', self.kwargs['pk'])


def check_possible_tasks(username, id_from, id_to):
    try:
        task_from = db.get_tasks(username, id_from)
        task_from.is_parent(id_to)
    except CycleError:
        return False
    else:
        return True


@login_required
def move_task(request, pk):
    username = request.user.username
    task = db.get_tasks(username, pk)
    pks_to_exclude = [pk] if not task.parent_task else [pk, task.parent_task.pk]
    tasks = db.get_tasks(username).exclude(pk__in=pks_to_exclude)
    available_tasks = (t for t in tasks if check_possible_tasks(username, pk, t.pk))
    form = TaskMoveForm(request.POST or None, tasks=available_tasks)
    if request.method == 'POST':
        task_from = db.get_tasks(username=username, task_id=pk)

        if form.is_valid():
            if form.cleaned_data['to_main']:
                task_from.parent_task = None
                task_from.save()
                db.add_completed(username, 'task', task_from)

            elif request.POST.get('task_to', None):
                task_to = db.get_tasks(username=username, task_id=form.cleaned_data['task_to'])
                task_to.add_subtask(task_from)

            return redirect('homepage')
    return render(request, 'caleweb/task_move.html', {'form': form})


@login_required
def share_task(request, pk):
    users = db.get_users().exclude(nickname=request.user.username)
    form = TaskShareForm(request.POST or None, users=users)

    if request.method == 'POST':
        if form.is_valid():
            username = db.get_users(username=request.user.username)
            user_to = db.get_users(username=form.cleaned_data['user_to'])
            task_to_share = db.get_tasks(username, pk)
            user_to.apply_task(task_to_share)
            return redirect('homepage')
    return render(request, 'caleweb/task_share.html', {'form': form})


@login_required
def unshare_task(request, pk, name):
    username = request.user.username
    task = db.get_tasks(username, pk)
    performer = db.get_users(name)
    performer.detach_task(task)
    return redirect('tasks:detail', pk)


# ###T###A###S###K###S###################################


class PlanListView(LoginRequiredMixin, ListView):
    template_name = 'caleweb/plan_all.html'
    context_object_name = 'plans'

    def get_queryset(self):
        username = self.request.user.username
        return db.get_plans(username)


class PlanCreateView(LoginRequiredMixin, CreateView):
    model = Plan
    form_class = PlanModelForm
    template_name = 'caleweb/instance-form.html'

    def form_valid(self, form):
        username = self.request.user.username
        new_plan = form.save(commit=False)
        new_plan.period = parse_period(new_plan.period_type, self.request.POST['period'])
        new_plan.save()
        db.add_completed(username, 'plan', new_plan)
        return redirect('plans:all')


class PlanDeleteView(LoginRequiredMixin, DeleteView):
    model = Plan
    template_name = 'caleweb/confirm_delete-form.html'
    success_url = reverse_lazy('plans:all')

    def get_queryset(self):
        return db.get_plans(self.request.user.username)


@login_required
def plan_set_state(request, pk):
    username = db.get_users(request.user.username)
    plan = db.get_plans(username, pk)
    plan.set_state()
    return redirect('plans:all')


class PlanUpdateView(LoginRequiredMixin, UpdateView):
    model = Plan
    template_name = 'caleweb/instance-form.html'
    form_class = PlanModelForm
    success_url = reverse_lazy('plans:all')

    def get_initial(self):
        plan = db.get_plans(self.request.user.username, self.kwargs['pk'])
        return {'period': parse_period_to_view(plan.period_type, plan.period)}

    def form_valid(self, form):
        username = self.request.user.username
        new_plan = form.save(commit=False)
        new_plan.period = parse_period(new_plan.period_type, self.request.POST['period'])
        new_plan.save()
        db.add_completed(username, 'plan', new_plan)
        return redirect('plans:all')


# ###P###L###A###N###S##############################################


class ReminderListView(LoginRequiredMixin, ListView):
    model = Reminder
    template_name = 'caleweb/reminder-all.html'
    context_object_name = 'reminders'

    def get_queryset(self):
        username = self.request.user.username
        return db.get_reminders(username)


class ReminderCreateView(LoginRequiredMixin, CreateView):
    model = Reminder
    template_name = 'caleweb/instance-form.html'
    fields = ['remind_type', 'remind_before']

    def form_valid(self, form):
        username = self.request.user.username

calendoola_web/caleweb/templates/caleweb/includes/custom_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
        {% else %}
            {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
            <small style="color: black;" class="form-text">{{ field.help_text|striptags }}</small>
        {% endif %}
    </div>
{% endfor %}

calendoola_web/caleweb/templates/caleweb/includes/header.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'tasks:all' %}"
       style="font-family: 'BioRhyme Expanded', serif;"><b>Calendoola</b></a>
    {% if request.path != 'login' and  request.path != 'signup' %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link {% if 'tasks' in request.path %}active{% endif %}"
                   href="{% url 'tasks:all' %}">Tasks <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if 'plans' in request.path %}active{% endif %}"
                   href="{% url 'plans:all' %}">Plans
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if 'reminders' in request.path %}active{% endif %}"
                   href="{% url 'reminders:all' %}">Reminders
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <div class="dropdown">
                    <a class="nav-link {% if 'new' in request.path %}active{% endif %}"
                       style="cursor: pointer;" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-plus-circle"></i> Add
                    </a>
                    <div class="dropdown-menu" style="background-color: #343a40;">
                        <a href="{% url 'tasks:new' %}" class="btn" style="text-decoration: #000000; color: white;">
                            <i class="fas fa-thumbtack"></i> Task</a>
                        <a href="{% url 'plans:new' %}" class="btn" style="text-decoration: #000000; color: white;">
                            <i class="fas fa-tasks"></i> Plan</a>
                        <a href="{% url 'reminders:new' %}" class="btn"
                           style="text-decoration: #000000; color: white;">
                            <i class="far fa-bell"></i> Reminder</a>
                    </div>
                </div>
            </li>
            <li class="nav-item navbar-right" style="margin-left: 15vw; width: 30vw;">
                <form class="form-inline" action="{% url 'tasks:search' %}" method="get"
                      accept-charset="utf-8">
                    <div class="form-group" style="width:100%;">

                        <input name="data" class="form-control" type="text" style="width:100%;"
                               placeholder="Search task by tags or description">

                    </div>
                </form>
            </li>
        </ul>
        {% if 'tasks' in request.path %}
            <div class="dropdown nav-item">
                <a class="nav-link text-center" style="color: white; cursor: pointer;" data-toggle="dropdown">
                    Order by
                </a>
                <div class="dropdown-menu" style="padding: 0; margin: 0">
                    <div class="btn-group" style="width: 100%">
                        <p class="nav-link" style="margin: 0; width: 100%;">Priority</p>
                        <a href="{% url 'tasks:all' %}?order=priority&vec=asc"
                           style="color: black; padding-left: 0;"
                           class=" btn fas fa-chevron-up"></a>
                        <a href="{% url 'tasks:all' %}?order=priority&vec=desc"
                           style="color: black; padding-left: 0;"
                           class="btn fas fa-chevron-down"></a>
                    </div>
                    <div class="btn-group" style="width: 100%">
                        <p class="nav-link" style="margin: 0">Deadline</p>
                        <a href="{% url 'tasks:all' %}?order=deadline&vec=asc"
                           style="color: black; padding-left: 0;"
                           class=" btn fas fa-chevron-up"></a>
                        <a href="{% url 'tasks:all' %}?order=deadline&vec=desc"
                           style="color: black; padding-left: 0;"
                           class="btn fas fa-chevron-down"></a>
                    </div>
                    <div class="btn-group" style="width: 100%">
                        <p class="nav-link" style="margin: 0">Creating</p>
                        <a href="{% url 'tasks:all' %}?order=created_at&vec=asc"
                           style="color: black; padding-left: 0;"
                           class=" btn fas fa-chevron-up"></a>
                        <a href="{% url 'tasks:all' %}?order=created_at&vec=desc"
                           style="color: black; padding-left: 0;"
                           class="btn fas fa-chevron-down"></a>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="dropdown nav-item">
            <button class="btn btn-secondary text-center" type="button" data-toggle="dropdown">
                {{ request.user.username|upper }}
            </button>
            <div class="dropdown-menu"
                 style="background-color: #343a40; left: auto; right: -20px;  border-radius: 20px">
                <a style="color: white;" class="nav-link text-center" href="{% url 'tasks:archive' %}">Archive</a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'logout' %}" class="nav-link text-center" style="color: white;">Exit</a>
            </div>
        </div>
    {% endif %}
</nav>

calendoola_web/caleweb/templates/caleweb/includes/notifications.html
<div class="message-block d-flex justify-content-center flex-column align-items-center">
    {% for message in messages %}
        <button class="alert {{ message.tags }} text-truncate" type="button" data-dismiss="alert" style="width: 20%">
            {{ message }}
        </button>
    {% endfor %}
</div>